semi: false
tabWidth: 2
useTabs: false
printWidth: 100
singleQuote: true
trailingComma: es5
bracketSpacing: true
proseWrap: preserve
overrides:
  - files: src/**/*.ts
    options:
      parser: typescript
  - files: src/**/*.tsx
    options:
      parser: typescript
  - files: src/**/*.css
    options:
      singleQuote: false
plugins: ['prettier-plugin-organize-imports', 'prettier-plugin-tailwindcss']